apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jacm-test-com-tls
spec:
  secretName: jacm-test-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jacm-test.com
  dnsNames: 
    - jacm-test.com
    - www.jacm-test.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jacm-test.com
          - www.jacm-test.com
